[package]
name = "rust_rocket_base_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
failure = {version = "0.1.8", features = ["derive"] }